<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "thdfilemanager"
 *
 * Auto generated by Extension Builder 2015-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dateimanager',
	'description' => 'Frontend-Dateiverwaltung',
	'category' => 'plugin',
	'author' => 'Thomas Demel',
	'version' => '0.3.3',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'constraints' => array(
		'depends' => array(
			'php' => '5.5',
			'typo3' => '6.2',
			'vhs' => '2.3.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);